default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: check_invoice_development

test:
  <<: *default
  database: check_invoice_test

production:
  <<: *default
  database: check_invoice_production
